[package]
name = "npcap-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["non_raw"]
non_raw = []
raw = []

[dependencies]
libc = "0.2"
pktparse = "0.7.1"

[build-dependencies]
bindgen = "0.60.1"
